from app.crud.branches import (
    create_branch,
    delete_branch,
    get_branch,
    get_branch_by_code,
    get_branches,
    get_branches_by_department,
    update_branch,
)
from app.crud.departments import (
    create_department,
    delete_department,
    get_department,
    get_department_by_code,
    get_departments,
    update_department,
)
from app.crud.courses import (
    create_course,
    delete_course,
    get_course,
    get_course_by_code,
    get_course_prerequisites,
    get_courses,
    get_courses_lite,
    search_courses,
    set_course_prerequisites,
    update_course,
)
from app.crud.curriculum import (
    add_curriculum_course,
    create_curriculum,
    create_elective_basket,
    delete_curriculum,
    delete_elective_basket,
    get_curricula,
    get_curricula_by_branch,
    get_curriculum,
    get_curriculum_courses,
    get_elective_baskets,
    remove_curriculum_course,
    update_curriculum,
    update_elective_basket,
)

from app.crud.reviews import (
    create as create_review,
    delete as delete_review,
    get_all as get_reviews,
    get_by_course as get_review_by_course,
    get_by_id as get_review_by_id,
    moderate as moderate_review,
)
from app.crud.announcements import (
    create_announcement,
    delete_announcement,
    get_announcement,
    get_announcements,
    get_announcements_by_category,
    get_pinned_announcements,
    update_announcement,
)
from app.crud.faculty import (
    create_faculty,
    delete_faculty,
    get_faculty,
    get_faculty_by_department,
    get_faculty_by_email,
    get_faculty_list,
    update_faculty,
)
from app.crud.resources import (
    create_resource,
    delete_resource,
    get_resource,
    get_resources,
    get_resources_by_category,
    update_resource,
)
from app.crud.team import (
    create as create_team_member,
    delete as delete_team_member,
    get_all as get_team_members,
    get_by_id as get_team_member_by_id,
    update as update_team_member,
)

__all__ = [
    "create_branch",
    "get_branch",
    "get_branch_by_code",
    "get_branches",
    "get_branches_by_department",
    "update_branch",
    "delete_branch",
    "create_department",
    "get_department",
    "get_department_by_code",
    "get_departments",
    "update_department",
    "delete_department",
    "create_course",
    "get_course",
    "get_course_by_code",
    "get_courses",
    "get_courses_lite",
    "update_course",
    "delete_course",
    "get_course_prerequisites",
    "set_course_prerequisites",
    "search_courses",
    "create_curriculum",
    "get_curriculum",
    "get_curricula",
    "get_curricula_by_branch",
    "update_curriculum",
    "delete_curriculum",
    "get_curriculum_courses",
    "add_curriculum_course",
    "remove_curriculum_course",
    "get_elective_baskets",
    "create_elective_basket",
    "update_elective_basket",
    "delete_elective_basket",
    "get_reviews",
    "get_review_by_id",
    "get_review_by_course",
    "create_review",
    "moderate_review",
    "delete_review",
    "get_team_members",
    "get_team_member_by_id",
    "create_team_member",
    "update_team_member",
    "delete_team_member",
    "create_announcement",
    "get_announcement",
    "get_announcements",
    "get_announcements_by_category",
    "get_pinned_announcements",
    "update_announcement",
    "delete_announcement",
    "create_faculty",
    "get_faculty",
    "get_faculty_by_department",
    "get_faculty_by_email",
    "get_faculty_list",
    "update_faculty",
    "delete_faculty",
    "create_resource",
    "get_resource",
    "get_resources",
    "get_resources_by_category",
    "update_resource",
    "delete_resource",
]
