"""add branch_id and batch_year to faculty

Revision ID: 060c33fd601b
Revises: e95e5bb2d54f
Create Date: 2026-07-15 19:20:39.451772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060c33fd601b'
down_revision: Union[str, Sequence[str], None] = 'e95e5bb2d54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
FACULTY_BRANCH_FK = "fk_faculty_branch_id_branches"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('faculty', sa.Column('batch_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_faculty_branch_id'), 'faculty', ['branch_id'], unique=False)
    op.create_foreign_key(
        FACULTY_BRANCH_FK,
        'faculty',
        'branches',
        ['branch_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FACULTY_BRANCH_FK, 'faculty', type_='foreignkey')
    op.drop_index(op.f('ix_faculty_branch_id'), table_name='faculty')
    op.drop_column('faculty', 'batch_year')
    op.drop_column('faculty', 'branch_id')
    # ### end Alembic commands ###
