"""drop student_id from course_reviews

Revision ID: cb40820eb896
Revises: 010
Create Date: 2026-07-06 11:23:17.846570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb40820eb896'
down_revision: Union[str, Sequence[str], None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_column('course_reviews', 'student_id')
    op.drop_constraint('uq_faculty_email', 'faculty', type_='unique')
    op.drop_index('ix_faculty_email', table_name='faculty')
    op.create_index(op.f('ix_faculty_email'), 'faculty', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_email'), table_name='faculty')
    op.create_index('ix_faculty_email', 'faculty', ['email'], unique=False)
    op.create_unique_constraint('uq_faculty_email', 'faculty', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('course_reviews', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
