"""add specialization to curricula

Revision ID: e95e5bb2d54f
Revises: cb40820eb896
Create Date: 2026-07-06 18:22:27.427126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95e5bb2d54f'
down_revision: Union[str, Sequence[str], None] = 'cb40820eb896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('specialization', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_curricula_specialization'), 'curricula', ['specialization'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curricula_specialization'), table_name='curricula')
    op.drop_column('curricula', 'specialization')
    # ### end Alembic commands ###
