"""add pdf_link to curriculum_courses

Revision ID: fc877c918349
Revises: 060c33fd601b
Create Date: 2026-07-27 15:31:17.381656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc877c918349'
down_revision: Union[str, Sequence[str], None] = '060c33fd601b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_courses', sa.Column('pdf_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_courses', 'pdf_link')
    # ### end Alembic commands ###
